name = "deploy"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
# plinth relies on gleam_http which overrides ffi.mjs
gleam_json = ">= 1.0.0 and < 3.0.0"
# gleam_http_native
gleam_http = ">= 3.6.0 and < 4.0.0"
snag = ">= 0.3.0 and < 1.0.0"
pojo = ">= 1.0.0 and < 2.0.0"
midas = ">= 0.4.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
