name = "pojo"
version = "1.0.1"
target = "javascript"

description = "Plain object encoding for some common Gleam types"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "gleamtours" }
links = [{ title = "Gleam Tours", href = "https://gleamtours.com" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
